services:
  postgres_db:
    image: postgres:15
    container_name: vet_clinic_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petwell-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vet_clinic_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_COOKIE_NAME: ${REFRESH_TOKEN_COOKIE_NAME}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
      PORT: 3000
      NODE_ENV: production
      # Uncomment if implementing these features
      # SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      # TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      # TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      # TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    # Uncomment for development to enable live reloading
    # volumes:
    #   - ./backend/src:/app/src
    #   - ./backend/prisma:/app/prisma
    networks:
      - petwell-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vet_clinic_frontend
    restart: unless-stopped
    environment:
      PORT: 3001
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${BACKEND_URL:-http://localhost:3000}
    ports:
      - "3001:3001"
    depends_on:
      - backend
    # Uncomment for development to enable live reloading
    # volumes:
    #   - ./frontend/src:/app/src
    #   - ./frontend/public:/app/public
    networks:
      - petwell-net

volumes:
  postgres_data:

networks:
  petwell-net:
    driver: bridge
